import { beforeEach, expect, jest, test } from '@jest/globals';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { setConsent } from './consent';
import { getPlayHistory, savePlayHistory, updatePlayHistoryProgress, upsertPlayHistory, type PlayHistoryItem } from './playHistory';
jest.mock('@react-native-async-storage/async-storage',()=>require('@react-native-async-storage/async-storage/jest/async-storage-mock'));
const item=(id:number,watchedAt=id):PlayHistoryItem=>({type:'movie',id,title:`Movie ${id}`,poster_path:null,backdrop_path:null,date:'',vote_average:5,watchedAt});
beforeEach(()=>AsyncStorage.clear());
test('does not persist before consent and caps at 20 unique media',async()=>{await upsertPlayHistory({...item(1),watchedAt:undefined} as never);expect(await getPlayHistory()).toEqual([]);await setConsent('accepted');await savePlayHistory([...Array(25)].map((_,i)=>item((i%22)+1,i)));expect(await getPlayHistory()).toHaveLength(20);});
test('keys TV progress by episode and clamps progress',async()=>{await setConsent('accepted');await upsertPlayHistory({...item(7),type:'tv',season:2,episode:3});await updatePlayHistoryProgress({type:'tv',id:7,season:2,episode:3,positionSeconds:200,durationSeconds:100});expect((await getPlayHistory())[0]).toMatchObject({progress:1,positionSeconds:200});expect(await updatePlayHistoryProgress({type:'tv',id:7,season:2,episode:4,positionSeconds:10,durationSeconds:100})).toBe(false);});
test('rejects corrupt arrays',async()=>{await AsyncStorage.setItem('binje:mobile:play-history:v1','[{"id":1}]');expect(await getPlayHistory()).toEqual([]);});
